#!/bin/bash

prev=a
SPOILER="I watched Avengers: Endgame. Thanos d**s..."

while ((1))
do
	if [[ -e log.txt ]]
	then
		cur=$( tail -n 1 log.txt )
		if [[ $cur != $prev ]] 
		then
			if [ "$SPOILER" = "$cur" ]; then
				echo "Spoiler Alert!"
			else
				echo $cur
			fi
			prev=$cur
		fi
	fi
done
